### ISSUE TITLE
Fix watchStore

### ISSUE THREAD

**Issue by adriaanwm** [staydecent/wasmuth#21] opened 2018-04-19 21:25 UTC
Watch store doesn't work when state at path is removed. Here's a working version.

```
const watchStore = (subscribe, getState) => (path, fn) => {
  let oldValue
  const watch = () => {
    const newValue = getPath(path, getState())
    if (!equal(oldValue, newValue)) {
      fn(oldValue, newValue)
      oldValue = newValue
    }
  }
  watch()
  subscribe(watch)
}
```

**Comment by staydecent** [comment] 2018-04-30 17:46
@adriaanwm 

Could not reproduce: https://github.com/inputlogic/with-preact/pull/40

let me know more details on how to reproduce and I can re-open, but closing for now.

**Closed as completed** 2018-04-30 17:47 UTC
Labels: invalid

**Comment by adriaanwm** [comment] 2018-04-30 17:59
```
import {watchPath, dispatch, remove, getState, set} from '/store'

watchPath(['example', 'nested'], () => console.log('fired'))

export const Example = ({url, modals = {}}) =>
  <div>
    <h1>Example</h1>
    <button onClick={() => dispatch(W.path('example.nested', getState()) ? remove('example') : set('example.nested', 'Hi'))}>click</button>
  </div>

export default Example
```
@staydecent it's actually only if you remove an object that is not as deeply nested as the watchPath path (eg. watch path at `example.nested.value` and remove `example` object, then watchPath doesn't fire)
